i18nText = {
    "en": {
        'langEn': "EN",
        'langDe': "DE",
        'map': "Map",
        'data': "Data",
        'aggregation': "Aggregation",
        'configuration': 'Configuration',
        'color_measure': 'Color Measure',
        'size_measure': 'Size Measure',
        'ok': 'OK',
        'summary': 'Summary',
        'about_us_link': 'About',
        'about_us_name': 'About Us',
        'about_us_headline': 'Radiological Cooperative Network on the COVID-19 Pandemic',
        'about_us_part_1': 'The project will be the first of its scale to establish a nationwide infrastructure for structured collection of radiologic data from Covid-19 cases. On the one hand this will allow to further utilize the in real time diagnosed and analyzed Covid-19 suspected pneumonia cases. On the other hand, it can provide highly structured data, for example, to support AI developments.',
        'about_us_part_2': 'The data serve, on the one hand, as a valuable decision-making basis for epidemiological studies, situation assessments and early warning mechanisms. On the other hand, it offers the possibility to automate diagnostic and image-processing steps.',
        'privacy_policy': 'Privacy Policy',
        'impressum': 'Impressum',
		'color_settings': 'Color Settings',
		'color_settings_desc': 'Preview:',
        'login_header': 'Member Login',
        'username': 'Username',
        'password': 'Password',
        'username_empty': 'Please enter valid username',
        'password_empty': 'Please enter valid password',
        'login_failed': 'Login failed - Please check your username and password',
        'login_success': 'Login Successful',
        'profile_tooltip': 'Profile / Logout',
        'profile_header': 'Profile Settings',
        'profile_logged_in_as': 'Logged in as',
        'dark_mode': 'Dark Mode',
        'light_mode': 'Light Mode',
        'use_third_color': 'Use third color',
        'previous_month': 'Previous Month',
        'previous_day': 'Previous Day',
        'next_day': 'Next Day',
        'next_month': 'Next Month',
        'color_presets': 'Color Presets (Click to apply)',
        'date_card': 'Date Selection',
        'legend_card': 'Legend',
        'average_indicators': 'Average Indicators',
        'no_token': 'No Token - Please contact admin',
        'reveal_token': 'Reveal API Token',
        'tour_link': 'Start Tour',
        'feedback_form_link': 'Feedback Form',
        'data_download_card': 'Data Download (CSV)',
        'filter': 'Location Filter',
        'filter_description': 'Select locations which should be shown on the map and used for the calculations in "Data" and "Aggregation" view.\nIf the selection is empty, all locations will be shown'
    },
    "de": {
        'langEn': "EN",
        'langDe': "DE",
        'map': "Karte",
        'data': "Daten",
        'aggregation': "Aggregation",
        'configuration': 'Einstellungen',
        'color_measure': 'POI Farbe',
        'size_measure': 'POI Größe',
        'ok': 'OK',
        'summary': 'Zusammenfassung',
        'about_us_link': 'Über Uns',
        'about_us_name': 'Über Uns',
        'about_us_headline': 'Radiological Cooperative Network zur COVID-19 Pandemie',
        'about_us_part_1': 'Das Projekt wird als erstes dieser Größenordnung eine landesweite Infrastruktur zur strukturierten Erfassung radiologischer Daten von Covid-19-Fällen errichten. Der Datenbestand wird zum einen die in Echtzeit befundeten und analysierten Daten Covid-19-verdächtiger Pneumoniefälle nutzbar machen. Zum anderen können hochstrukturierte Daten, beispielsweise zur Unterstützung von KI-Entwicklungen, bereitgestellt werden.',
        'about_us_part_2': 'Die Daten dienen einerseits als wertvolle Entscheidungsgrundlage für epidemiologische Studien, Lageeinschätzungen und Frühwarnmechanismen. Andererseits bietet sich die Möglichkeit für die Automatisierung diagnostischer und bildverarbeitender Schritte.',
        'privacy_policy': 'Datenschutz',
        'impressum': 'Impressum',
		'color_settings': 'Farbeinstellungen',
		'color_settings_desc': 'Vorschau:',
        'login_header': 'Benutzer Login',
        'username': 'Benutzername',
        'password': 'Passwort',
        'username_empty': 'Bitte gültigen Benutzernamen eingeben',
        'password_empty': 'Bitte gültiges Passwort eingeben',
        'login_failed': 'Login Fehlgeschlagen - Bitte überprüfe den Benutzernamen und das Passwort',
        'login_success': 'Login Erfolgreich',
        'profile_tooltip': 'Profil / Logout',
        'profile_header': 'Profil-Einstellungen',
        'profile_logged_in_as': 'Angemeldet als',
        'dark_mode': 'Dunkler Modus',
        'light_mode': 'Heller Modus',
        'use_third_color': 'Dritte Farbe verwenden',
        'previous_month': 'Vorheriger Monat',
        'previous_day': 'Vorheriger Tag',
        'next_day': 'Nächster Tag',
        'next_month': 'Nächster Monat',
        'color_presets': 'Farb-Presets (Zum Anwenden anklicken)',
        'date_card': 'Datum Auswahl',
        'legend_card': 'Legende',
        'average_indicators': 'Durchschnitt Indikatoren',
        'no_token':  'Kein Token - Bitte Admin anfragen',
        'reveal_token': 'API Token anzeigen',
        'tour_link': 'Tour Starten',
        'feedback_form_link': 'Feedback Formular',
        'data_download_card': 'Daten Download (CSV)',
        'filter': 'Standort Filter',
        'filter_description': 'Wähle alle Standorte, die auf der Karte angezeigt und für die Berechnungen in den Ansichten "Daten" und "Aggregation" verwendet werden sollen.\nFalls die Auswahl leer ist, werden automatisch alle Standorte angezeigt.'
    }
}
