FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-tuda-local"
LABEL VERSION="0.1.0-vdev"
LABEL CI_IGNORE="False"

COPY dags/dag_tuda_calc_quality_measures.py /tmp/dags/
COPY dags/dag_tuda_calc_quality_measures_trigger_rule.json /tmp/dags/
COPY dags/dag_service_tuda_aggregate_quality_measures.py /tmp/dags/

COPY dags/tuda/AggregateQmDataOperator.py /tmp/dags/tuda/
COPY dags/tuda/Dcm2ItkOperator.py /tmp/dags/tuda/
COPY dags/tuda/DcmSr2JsonOperator.py /tmp/dags/tuda/
COPY dags/tuda/GetAllQmDsrOperator.py /tmp/dags/tuda/
COPY dags/tuda/Json2DcmSrOperator.py /tmp/dags/tuda/
COPY dags/tuda/MergeQmOutputsOperator.py /tmp/dags/tuda/
COPY dags/tuda/QmArtifactsOperator.py /tmp/dags/tuda/
COPY dags/tuda/QmDicePredictorOperator.py /tmp/dags/tuda/
COPY dags/tuda/PrepareInputDataOperator.py /tmp/dags/tuda/

COPY models/tuda /tmp/models/tuda
